### ISSUE TITLE
More granular padding controls

### ISSUE THREAD

**Issue by AnishDe12020** [rishimohan/pika#8]
Currently, the options for padding seem a bit limited to me. We can have more granular control, maybe a slider or maybe even an input to set an exact numeric value.

P.S. Willing to work on the issue. You can assign it to me if the idea seems fine.

**Comment by rishimohan** [comment]
@AnishDe12020 Hi Anish, you're right! I've been thinking to add finer controls since some time now, also a way to quickly change options in settings without much clicks. Also there are some issues with aspect ratio option in certain cases, I'm planning to work on solving these together. 

Would love your contribution but since this one will need change in base logic I would want to work on it. I'll post an update for your feedback when it's done :)

**Comment by AnishDe12020** [comment]
Cool, looking forward to it!!!

**Comment by rishimohan** [comment]
@AnishDe12020 I've explored a new way to control padding through a range slider, less clicks and more padding options. Let me know what you think of it, it's deployed here - pika.rishimohan.me

**Comment by AnishDe12020** [comment]
Awesome, I like it

**Comment by rishimohan** [comment]
@AnishDe12020 I'll explore more into it and see if I can make it even matter. Closing the issue for now, let me know if you have more feedback, thanks :)
